### ISSUE TITLE
"Unknown function string_new" with gobject-introspection 1.70.0

### ISSUE THREAD

**Issue by foutrelis** [gtkd-developers/GlibD#12]
Seems to build with gobject-introspection 1.68.0 + glib 2.70.0 but I'm getting the following error with gobject-introspection 1.70.0:

```
Run-time dependency glib-2.0 found: YES 2.70.0
Run-time dependency gmodule-2.0 found: YES 2.70.0
Run-time dependency gobject-2.0 found: YES 2.70.0
Run-time dependency gio-2.0 found: YES 2.70.0
Run-time dependency gobject-introspection-1.0 found: YES 1.70.0
Program girtod found: YES (/usr/bin/girtod)
Message: Generating D interfaces from GIR...

../meson.build:37:4: ERROR: Problem encountered: Unable to build D intefaces from GIR:
Error /build/glibd/src/GlibD-2.3.0/src/APILookupGLib.txt(1988): Unknown function string_new
```

A quick search turned up https://gitlab.gnome.org/GNOME/gobject-introspection/-/issues/399 but I'm not sure what needs to be fixed. :)

**Comment by MikeWey** [comment]
Looks like we no longer need to put the string functions in the correct location manually.

**Comment by arrowd** [comment]
Bumped into this while packaging this project for FreeBSD. Can you please make a new release, so that we won't have to pull in patches?

**Comment by MikeWey** [comment]
tagged v2.4.0
