### ISSUE TITLE
Fails to build on Fedora 32 (glib2-2.63.5)

### ISSUE THREAD

**Issue by Conan-Kudo** [gtkd-developers/GlibD#7]
GlibD 2.1.0 fails to build on Fedora 32 with gir-to-d 0.20.0 and glib2 2.63.5.

The error generated:
```
Message: Generating D interfaces from GIR...
meson.build:37:4: ERROR: Problem encountered: Unable to build D intefaces from GIR:
Error /usr/share/gir-1.0/GLib-2.0.gir(150): Unexpected tag: function-macro in GirPackage: glib
```

The full build log: [glibd-2.1.0-3.fc32-build.log.txt](https://github.com/gtkd-developers/GlibD/files/4241493/glibd-2.1.0-3.fc32-build.log.txt)

**Comment by MikeWey** [comment]
Updating gir-to-d to version 0.20.0 should fix this.

**Comment by Conan-Kudo** [comment]
Hmm, that last build wasn't with gir-to-d 0.20.0, but this one is and I get a different error: 
[glibd-2.1.0-3.fc32-build.log.txt](https://github.com/gtkd-developers/GlibD/files/4242393/glibd-2.1.0-3.fc32-build.log.txt)

**Comment by MikeWey** [comment]
I've testet this with version 2.63.1 i got the same error so afaik it should be fixed now.
